# Generated by Django 3.2.13 on 2022-04-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muestro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='profesor',
            field=models.CharField(default='Some String', max_length=255),
        ),
    ]
