# Generated by Django 3.2.13 on 2022-04-25 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Muestro', '0004_auto_20220425_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='profesor',
        ),
    ]
